CREATE TABLE IF NOT EXISTS historic_weather (
    id SERIAL PRIMARY KEY,
    num_poste INTEGER NOT NULL,
    nom_usuel VARCHAR(100),
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    alti INTEGER,
    dept VARCHAR(3),
    annee INTEGER NOT NULL,
    mois INTEGER NOT NULL,
    tm DOUBLE PRECISION,
    tx DOUBLE PRECISION,
    tn DOUBLE PRECISION,
    rr DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS predictions_2026 (
    id SERIAL PRIMARY KEY,
    num_poste INTEGER NOT NULL,
    dept VARCHAR(3) NOT NULL,
    min_1 DOUBLE PRECISION, max_1 DOUBLE PRECISION,
    min_2 DOUBLE PRECISION, max_2 DOUBLE PRECISION,
    min_3 DOUBLE PRECISION, max_3 DOUBLE PRECISION,
    min_4 DOUBLE PRECISION, max_4 DOUBLE PRECISION,
    min_5 DOUBLE PRECISION, max_5 DOUBLE PRECISION,
    min_6 DOUBLE PRECISION, max_6 DOUBLE PRECISION,
    min_7 DOUBLE PRECISION, max_7 DOUBLE PRECISION,
    min_8 DOUBLE PRECISION, max_8 DOUBLE PRECISION,
    min_9 DOUBLE PRECISION, max_9 DOUBLE PRECISION,
    min_10 DOUBLE PRECISION, max_10 DOUBLE PRECISION,
    min_11 DOUBLE PRECISION, max_11 DOUBLE PRECISION,
    min_12 DOUBLE PRECISION, max_12 DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_historic_dept ON historic_weather(dept);
CREATE INDEX IF NOT EXISTS idx_historic_annee_mois ON historic_weather(annee, mois);
CREATE INDEX IF NOT EXISTS idx_historic_dept_annee ON historic_weather(dept, annee, mois);
CREATE INDEX IF NOT EXISTS idx_predictions_dept ON predictions_2026(dept);
